### ISSUE TITLE
Run subscriptions as a different process from a rake task

### ISSUE THREAD

**Issue by night91** [keypup-io/cloudenvoy#41]
Is there is a way to run each subscription individually as its own process? For what I see, launching rails will also launch all the subscriptions.

**Comment by alachaum** [comment]
Hi @night91, when you say "launching" the subscriptions, are you referring to registering the subscribers to their topics?

The setup of each subscription/topic is done separately from launching rails. We propose several rake tasks for that purpose:
```bash
# Setup publishers (topics) and subscribers (subscriptions) in one go
bundle exec rake cloudenvoy:setup

# Or set them up individually
bundle exec rake cloudenvoy:setup_publishers
bundle exec rake cloudenvoy:setup_subscribers
```

**Comment by stevefolly** [comment]
I was about to ask a similar question, but I think this is what I'm wondering - forgive me if I'm wrong, but I think @night91 is asking whether it's possible to run the subscribers without starting the server on port 3000. For example, in a similar way to how you would start Sidekiq.  Given that you mention much about the microservice architecture, it doesn't seem to fit that you'd have the web server _and_ subscribers running in the same process.

**Comment by night91** [comment]
Hi @alachaum, sorry if I didn't transmit my question clearly. Indeed, I was referring to what @stevefolly appointed. 
Imagine I wanted to run in a GKE cluster, so I may want to run a deployment for each subscriber or to have a possibility to run a set of subscribers (ex: all subscribers for dead letter topics).

It would be cool if, with a rake task, we could run a subscriber (without staring the server).

One example for running a consumer for Apache Kafka is: https://github.com/zendesk/racecar#running-consumers

**Comment by stevefolly** [comment]
Looking through the README again, I'm not sure this will be possible, since the implementation uses the push method, registering a webhook with the Google Cloud.  Google Cloud will then call the webhook for each message received.   What I was looking for (and possibly you as @night91 by the sounds of it) is to use the pull method.

By using this library, I don't think it's possible to use the cloud Pub/Sub API in a local development environment either, since the webhook needs to be accessible from Google Cloud.

@alachaum  can you confirm please?

**Comment by night91** [comment]
@stevefolly the pull method is useful for situations such as Cloud Run. But you should still be able to run them without the server. Anyway, the pull method where it really shines. Is there any alternative, besides implementing your own stuffs as docs says?

**Comment by alachaum** [comment]
@stevefolly you're completely right. With Cloudenvoy, you do not need an "active agent" to pull/process messages. The application is configured to subscribe and receive messages via webhooks.

## Local development

In terms of local development, it's totally possible to use Cloudenvoy locally. To do so, just install the `pubsub emulator` via the `gcloud cli`. This emulator will mimic pub/sub locally and allow you to work in development without the need for an external tunnel (e.g. ngrok). See the the [Get started with Rails](https://github.com/keypup-io/cloudenvoy#get-started-with-rails) for an example of setup (I extracted the relevant steps below)

```sh
# Install the pub/sub emulator
gcloud components install pubsub-emulator
gcloud components update

# Start the emulator
gcloud beta emulators pubsub start
```

## Pull
At the moment, cloudenvoy does not offer a `pull` mechanism. But I'll consider it for future developments. I understand the `pull` approach can be very useful when apps run in a private environment with no accessible URLs.

In the meantime, you can still develop a small ruby agent that pulls messages from Pub/Sub and then use the whole Cloudenvoy logic to declare subscribers and process those messages. After all, the "receiving" part of Cloudenvoy is just a controller - it's a minor part of Cloudenvoy. This part can be replaced by a custom agent.


## Dividing processing
Having said that, if you're looking to "divide and conquer" on message processing, it's still possible to divide your app into multiple apps to process certain messages. E.g.
- One shared ruby library with core models and logic
- One sinatra/rails app using the shared library above and subscribing to `topic1`, `topic2`, `topic3`
- One sinatra/rails app using the shared library above and subscribing to `topic4`, `topic5`, `topic6`
